version: '3'
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=helloworld
  adminer:
    image: adminer
    ports:
      - 8080:8080